src/Entity/Conversation.php
<?php

namespace App\Entity;

use App\Repository\ConversationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConversationRepository::class)]
class Conversation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $titre = null;

    #[ORM\ManyToOne(inversedBy: 'conversations')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $idUser = null;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'idConversation')]
    private Collection $messages;

    private ?string $firstMessage = null;

    public function getFirstMessage(): ?string
    {
        return $this->firstMessage;
    }

    public function setFirstMessage(?string $msg): void
    {
        $this->firstMessage = $msg;
    }

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(?User $idUser): static
    {
        $this->idUser = $idUser;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setIdConversation($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getIdConversation() === $this) {
                $message->setIdConversation(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\UserRole;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $motDePasse = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(enumType: UserRole::class)]
    private ?UserRole $role = null;

    #[ORM\Column]
    private ?bool $estVerifie = null;

    /**
     * @var Collection<int, Conversation>
     */
    #[ORM\OneToMany(targetEntity: Conversation::class, mappedBy: 'idUser')]
    private Collection $conversations;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'idUser')]
    private Collection $messages;

    /**
     * @var Collection<int, Galerie>
     */
    #[ORM\OneToMany(targetEntity: Galerie::class, mappedBy: 'idUser')]
    private Collection $galeries;

    /**
     * @var Collection<int, Tarifs>
     */
    #[ORM\OneToMany(targetEntity: Tarifs::class, mappedBy: 'idUser')]
    private Collection $tarifs;

    public function __construct()
    {
        $this->conversations = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->galeries = new ArrayCollection();
        $this->estVerifie = false;
        $this->role = UserRole::USER;
        $this->tarifs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->motDePasse;
    }

    public function setMotDePasse(string $motDePasse): static
    {
        $this->motDePasse = $motDePasse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getRole(): ?UserRole
    {
        return $this->role;
    }

    public function setRole(UserRole $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function isEstVerifie(): ?bool
    {
        return $this->estVerifie;
    }

    public function setEstVerifie(bool $estVerifie): static
    {
        $this->estVerifie = $estVerifie;

        return $this;
    }

    /**
     * @return Collection<int, Conversation>
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): static
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations->add($conversation);
            $conversation->setIdUser($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): static
    {
        if ($this->conversations->removeElement($conversation)) {
            // set the owning side to null (unless already changed)
            if ($conversation->getIdUser() === $this) {
                $conversation->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setIdUser($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getIdUser() === $this) {
                $message->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Galerie>
     */
    public function getGaleries(): Collection
    {
        return $this->galeries;
    }

    public function addGalery(Galerie $galery): static
    {
        if (!$this->galeries->contains($galery)) {
            $this->galeries->add($galery);
            $galery->setIdUser($this);
        }

        return $this;
    }

    public function removeGalery(Galerie $galery): static
    {
        if ($this->galeries->removeElement($galery)) {
            // set the owning side to null (unless already changed)
            if ($galery->getIdUser() === $this) {
                $galery->setIdUser(null);
            }
        }

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->motDePasse;
    }

    public function getRoles(): array
    {
        return [$this->role?->value ?? 'ROLE_USER'];
    }

    public function eraseCredentials(): void
    {

    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @return Collection<int, Tarifs>
     */
    public function getTarifs(): Collection
    {
        return $this->tarifs;
    }

    public function addTarif(Tarifs $tarif): static
    {
        if (!$this->tarifs->contains($tarif)) {
            $this->tarifs->add($tarif);
            $tarif->setIdUser($this);
        }

        return $this;
    }

    public function removeTarif(Tarifs $tarif): static
    {
        if ($this->tarifs->removeElement($tarif)) {
            // set the owning side to null (unless already changed)
            if ($tarif->getIdUser() === $this) {
                $tarif->setIdUser(null);
            }
        }

        return $this;
    }
}

src/Form/ConversationType.php
<?php

namespace App\Form;

use App\Entity\Conversation;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConversationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('firstMessage', TextareaType::class, [
                'mapped' => false,
                'label' => 'Message'
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Conversation::class,
        ]);
    }
}

src/Controller/Admin/ConversationController.php
<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Repository\ConversationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/dashboard/conversations')]
class ConversationController extends AbstractController
{
    #[Route('/', name: 'app_admin_conversation_index', methods: ['GET'])]
    public function index(ConversationRepository $conversationRepository): Response
    {
        return $this->render('admin/conversation/index.html.twig', [
            'conversations' => $conversationRepository->findAll(),
        ]);
    }
}

src/Controller/User/ConversationController.php
<?php

namespace App\Controller\User;

use App\Entity\Conversation;
use App\Entity\Message;
use App\Form\MessageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/profile/conversation')]
final class ConversationController extends AbstractController
{
    #[Route('/{id}', name: 'app_conversation_show', methods: ['GET', 'POST'])]
    public function show(Conversation $conversation, Request $request, EntityManagerInterface $entityManager, int  $id): Response
    {
        $user = $this->getUser();

        if ($user !== $conversation->getIdUser() && !in_array('ROLE_ADMIN', $user->getRoles())) {
            throw $this->createAccessDeniedException('Accès interdit.');
        }

        $message = new Message();
        $message->setIdConversation($conversation);
        $message->setIdUser($user);

        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('app_conversation_show', ['id'=>$id], Response::HTTP_SEE_OTHER);
        }


        return $this->render('conversation/show.html.twig', [
            'conversation' => $conversation,
            'form' => $form,
        ]);
    }
}

templates/conversation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/conversation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chb Photo - Messagerie - {{ conversation.titre }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/conversation.css') }}" data-turbo-track="reload">
    <link rel="stylesheet" href="{{ asset('styles/tab/conversationTab.css') }}" data-turbo-track="reload">
    <link rel="stylesheet" href="{{ asset('styles/mobile/convesationMobile.css') }}" data-turbo-track="reload">
    <link rel="stylesheet" href="{{ asset('styles/forms.css') }}" data-turbo-track="reload">
{% endblock %}

{% block body %}
    <div class="glass-container return">
        <div class="glass-filter"></div>
        <div class="glass-overlay"></div>
        <div class="glass-specular"></div>
        <div class="glass-content">
            {% if 'ROLE_ADMIN' in app.user.roles %}
                <a href="{{ path('app_admin_conversation_index') }}">{{ ux_icon('heroicons:arrow-uturn-left') }}</a>
            {% else %}
                <a href="{{ path('app_profile') }}">{{ ux_icon('heroicons:arrow-uturn-left') }}</a>
            {% endif %}
        </div>
    </div>
    <div class="formulaire">
        <div class="glass-container conv-container">
            <div class="glass-filter"></div>
            <div class="glass-overlay"></div>
            <div class="glass-specular"></div>
            <div class="glass-content conv-content">
                <h2>{{ conversation.titre }}</h2>
                <ul class="conversation">
                    {% for message in conversation.messages %}
                        {% if 'ROLE_ADMIN' in message.idUser.roles %}
                            <li class="glass-container admin-msg">
                                <div class="glass-filter"></div>
                                <div class="glass-overlay"></div>
                                <div class="glass-specular"></div>
                                <div class="glass-content msg">
                                    {{ message.contenu }}
                                </div>
                            </li>
                            <p class="admin-date">{{ message.idUser.prenom }}
                                - {{ message.createdAt|date('d/m/Y H:i') }}</p>
                        {% else %}
                            <li class="glass-container user-msg">
                                <div class="glass-filter"></div>
                                <div class="glass-overlay"></div>
                                <div class="glass-specular"></div>
                                <div class="glass-content msg">
                                    {{ message.contenu }}
                                </div>
                            </li>
                            <p class="user-date">{{ message.idUser.prenom }}
                                - {{ message.createdAt|date('d/m/Y H:i') }}</p>
                        {% endif %}
                    {% else %}
                        <li>Aucun message</li>
                    {% endfor %}
                </ul>
                {{ include('conversation/_form.html.twig') }}
            </div>
        </div>
    </div>
    <script src="{{ asset('js/convScroll.js') }}" data-turbo-track="reload"></script>
{% endblock %}